config/routes.rb
Rails.application.routes.draw do
  root 'pages#comingsoon'

  namespace :admin do
    root to: "projets#index"
    resources :projets
    resources :articles
    resources :users
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  before_save :set_slug
  has_attached_file :image, styles: { medium: "800x800>", thumb: "300x300>", default_url: "/images/default.jpg" }


  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  belongs_to :user

	private
	  def set_slug
	  	self.slug = self.title.parameterize
	end

end

app/models/projet.rb
class Projet < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "800x800>", thumb: "300x300>" }

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
	has_attached_file :image, styles: { medium: "800x800>", thumb: "300x300>" }

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	has_many :articles
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    http_basic_authenticate_with name: ENV.fetch("ADMIN_NAME"), password: ENV.fetch("ADMIN_PASSWORD")
    before_filter :authenticate_admin

    def authenticate_admin
        # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Article.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Article.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/projets_controller.rb
module Admin
  class ProjetsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Projet.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Projet.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
  def index
  	@articles = Article.order(position: :desc)
  end

  def show
  	@article = Article.find_by(slug: params[:slug])

    if @article.nil?
  		redirect_to root_path
  	end
  	@user = User.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def comingsoon
    @disable_nav = true
  end


  def index
  	@articles = Article.all
    @Projets = Projet.all
  end

  def agence
  end

  def methode
  end

  def contact
  end

  def mentionslegales
  end

  def show

  	@article = Article.find_by(slug: params[:slug])

  if @article.nil?
  		redirect_to root_path
  end
  end

end

app/controllers/projet_controller.rb
class ProjetController < ApplicationController
  def index
  	@Projets = Projet.limit(15).in_groups_of(6, false)
  end

  def show
  	@Projets = Projet.all
  	@projet = Projet.find_by(slug: params[:slug])


  	if @projet.nil?
  		redirect_to root_path
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projet_helper.rb
module ProjetHelper
end

app/views/article/index.html.erb
	<div class="block">
        <div class="container">
          <img class="logosmg" alt="logo designisvital" src="http://res.cloudinary.com/design-is-vital/image/upload/v1476101591/LOGO5-06_lmqkuj.png">
          <br>
          <h1>Le Blog</h1>
          <p> de l'agence Design is Vital</p>
        </div>
    </div>

    <div class="prerow">
        <h1> Apprendre tous les jours comment maitriser l'UX </h1>
        <p>et découvrez des trics de designer !</p>
    </div>

<div class="bodyprojet">
    <% @articles.each do |article| %>
    <ul class="list-unstyled">
        <li class="product">
          <div class="product-upvote text-center">
            <i class="fa fa-caret-up"></i>
            <p><%= article.position %></p>
          </div>

          <a href="<%= articles_path(article.slug) %>"><img src="<%= article.image.url(:thumb) %>" alt="<% article.title %>" class="product-image img-rounded img-responsive"> </a>

          <div class="product-description">
            <!-- <h4 style="font-weight:400;color:#979797"><%= article.title %></h4>-->
            <h4><%= article.soustitre %></h4>
            <p style="color:#979797"><%= truncate(article.description, length: 90, escape: false) %> </p>
             <!--<p> Par <span style="color:#BABABA;"><%= article.user.name %></span>-->
            <br>
            <a class="styla" href="<%= articles_path(article.slug) %>">Lire l'article</a>
          </div>
        </li>
    </ul>
  <% end %>
</div>

app/views/article/show.html.erb
<div class="show">
	<div class="block">
	    <div class="container">
	    	<%= image_tag("http://res.cloudinary.com/design-is-vital/image/upload/v1476101591/LOGO5-06_lmqkuj.png", :class => "logosmg")%>  
	    	<br>
	        <h1>Article</h1>
	        <p>Pour enrichir tous les jours vos connaissances</p>
	    </div>
	</div>    

	<br>
	<div class="container">
		<h2 style="color:#FFED00"><%= @article.title %></h2>
		<h3> <%= @article.soustitre %> </h3>
		<p> écrit par <span style="font-weight:600;"><%= @article.user.name %></span> le <i><%= @article.created_at %></i></p>
		<br>
		<p><%= simple_format(@article.description).html_safe %></p>
		<br>
		 <!-- <img style="padding-top:50px;width:400px;" src="<%= @article.image.url(:medium) %>" alt="<% @article.title %>">-->
		<br>
		<br>	
	</div>
</div>

app/views/fields/paperclip_field/_form.html.erb
<%= f.label field.attribute %>
<%= f.file_field field.attribute %>

app/views/fields/paperclip_field/_index.html.erb
<%= image_tag field.thumbnail %>

app/views/fields/paperclip_field/_show.html.erb
<%= image_tag field.medium %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>DESIGN IS VITAL | Agence Digitale | UX Design </title>

  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Baloo+Bhai" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Suez+One" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lobster|Permanent+Marker|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">    <title>Design is Vital</title>


  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    </head>
    <body>

      <%= render "layouts/partials/nav" unless @disable_nav %>
			<%= yield %>
      <%= render "layouts/partials/footer" unless @disable_nav %>



        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    </body>
</html>

app/views/layouts/partials/_footer.html.erb
      <hr>
      <div class="footer">
        <div class="container">
            <!-- <img src="http://unsplash.it/250/250/?random" alt="" class="avatar logofooter">-->
          <div class="row">

            <div class="col-xs-6 col-sm-3">
              <%= image_tag("http://res.cloudinary.com/design-is-vital/image/upload/v1476101591/LOGO4-05_rk90ex.png", :class => "logofooter")%>
            </div>

            <div class="col-xs-6 col-sm-3">
              <h5>DESIGN IS VITAL</h5><p>  3, Sente du Clos d'Arcy <br> 78300 POISSY <br> </p><h5>Tel : 01 00 00 00 00 <br> contact@designisvital.co </h5>
            </div>

            <div class="col-xs-6 col-sm-3">
             <ul class="foot">
              <li><h5>L'AGENCE</h5></li>
              <li><%= link_to "ACCUEIL", root_path %></li>
               <li><%= link_to "AGENCE", agence_path %></li>
               <li><%= link_to "RÉALISATIONS", projets_path %></li>
               <li><%= link_to "MÉTHODE", methode_path %></li>
               <li><a href="https://fr.pinterest.com/designisvital75/" target="_blanc">INSPIRATION</a></li>
               <li><%= link_to "BLOG", article_path %></li>
             </ul>
           </div>

           <div class="col-xs-6 col-sm-3">
            <ul class="foot">
             <li><h5>INFOS</h5></li>
             <li><%= link_to "CONTACT", contact_path %></li>
             <li><%= link_to "MENTIONS LEGALES", mentionslegales_path %></li>
           </ul>
           <ul class="socialfoot">
              <li><h5>SUIVEZ-NOUS</h5></li><br>
              <li><a href="http://facebook.com/designisvital"><i class="fa fa-facebook-official" aria-hidden="true"></i></a></li>
              <li><a href="https://www.instagram.com/designisvital/"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
              <li><a href="https://fr.pinterest.com/designisvital75/"><i class="fa fa-pinterest-square" aria-hidden="true"></i></a></li>
              <li><a href="https://twitter.com/design_is_vital"><i class="fa fa-twitter-square" aria-hidden="true"></i></a></li>
           </ul>
        </div>
      </div>

app/views/layouts/partials/_nav.html.erb
      <nav class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar top-bar"></span>
              <span class="icon-bar middle-bar"></span>
              <span class="icon-bar bottom-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= root_path %>">
              <%= image_tag("http://res.cloudinary.com/design-is-vital/image/upload/v1476101591/LOGO5-06_lmqkuj.png", :class => "Brand")%>
            </a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-left">
              <li><%= link_to "ACCUEIL", root_path %></li>
              <li><%= link_to "AGENCE", agence_path %></li>
              <li><%= link_to "RÉALISATIONS", projets_path %></li>
              <li><%= link_to "MÉTHODE", methode_path %></li>
              <!--<li><a href="https://fr.pinterest.com/designisvital75/" target="_blanc">INSPIRATION</a></li>-->
              <li><%= link_to "BLOG", article_path %></li>
              <li><%= link_to "CONTACT", contact_path %></li>
            </ul>

            <ul class="social navbar-right">
              <li><a href="http://facebook.com/designisvital"><i class="fa fa-facebook-official" aria-hidden="true"></i></a></li>
              <li><a href="https://www.instagram.com/designisvital/"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
              <li><a href="https://fr.pinterest.com/designisvital75/"><i class="fa fa-pinterest-square" aria-hidden="true"></i></a></li>
              <li><a href="https://twitter.com/design_is_vital"><i class="fa fa-twitter-square" aria-hidden="true"></i></a></li>
            </ul>
          </div><!--/.navbar-collapse -->
        </div>
      </nav>

app/views/pages/comingsoon.html.erb
 <div class="container">
      <div class="row">
        <div class="col-md-4 collines">
            <hr style="border-top: 2px solid #FFED00;width:20px;margin-left:0px;">
            <!--<p class="lines">Nouveau bureaux</p>-->
             <p class="lines">Nouvelle identité</p>
              <p class="lines"><strong>Nouveau site...</strong></p>
        </div>
        <div class="col-md-4 centercol">
          <%= image_tag("logocs.png", :class => "img")%>
          <p class="subtitle">Agence <strong>Digitale</strong> <br>spécialisée en <strong>UX Design</strong></p>
          <h1 class="title">Coming <span class="color">Soon<span></h1>
        </div>
        <div class="col-md-4 rightcol">
          <ul class="social">
              <hr class="hrsocial">
              <li><p>SUIVEZ-NOUS SUR</p></li><br>
              <li><a href="http://facebook.com/designisvital"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
              <li><a href="https://www.instagram.com/designisvital/"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
              <li><a href="https://fr.pinterest.com/designisvital75/"><i class="fa fa-pinterest-square" aria-hidden="true"></i></a></li>
              <li><a href="https://twitter.com/design_is_vital"><i class="fa fa-twitter-square" aria-hidden="true"></i></a></li>
           </ul>
        </div>
      </div>
    </div><!-- /.container -->

app/views/pages/contact.html.erb
<!-- Change the width and height values to suit you best -->
<div class="typeform-widget" data-url="https://florianceo1.typeform.com/to/tTSFPj" data-text="Contact" style="width:100%;height:500px;"></div>
<script>(function(){var qs,js,q,s,d=document,gi=d.getElementById,ce=d.createElement,gt=d.getElementsByTagName,id='typef_orm',b='https://s3-eu-west-1.amazonaws.com/share.typeform.com/';if(!gi.call(d,id)){js=ce.call(d,'script');js.id=id;js.src=b+'widget.js';q=gt.call(d,'script')[0];q.parentNode.insertBefore(js,q)}})()</script>
<div style="font-family: Sans-Serif;font-size: 12px;color: #999;opacity: 0.5; padding-top: 5px;">Powered by<a href="https://www.typeform.com/examples/?utm_campaign=tTSFPj&amp;utm_source=typeform.com-4600295-Basic&amp;utm_medium=typeform&amp;utm_content=typeform-embedded-poweredbytypeform&amp;utm_term=FR" style="color: #999" target="_blank">Typeform</a></div>

app/views/pages/index.html.erb
      <video id="video-background" preload muted autoplay loop>
        <source src="http://media.istockphoto.com/videos/business-people-architecture-and-team-work-concept-close-up-of-team-video-id498510508">
      </video>
      <!--<video id="video-background" preload muted autoplay loop>
        <source src="http://ak6.picdn.net/shutterstock/videos/6565346/preview/stock-footage-close-up-hands-typing-on-keyboards-in-office-business-people-typing.mp4">
      </video>-->

     <div class="jumbotron">
        <div class="container">
          <img class="logosmg" alt="logo designisvital" src="http://res.cloudinary.com/design-is-vital/image/upload/v1476101591/LOGO5-06_lmqkuj.png">
            <div class="wrapper">
              <h1><span class="focus">Agence spécialisée en design <br>d'expérience utilisateur</span></h1>
            </div>
            <div class="wrapper_text">
            <p><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>Application Web et Mobile - Design d'Expériences et d'Interfaces. </p> 
            </div>
        </div>
      </div>

      
        <div class="logosbar">
          <div class="container logonainer">
            <div class="row">
              <div class="col-md-2">
                <a href="#"><img src="http://res.cloudinary.com/design-is-vital/image/upload/v1476028395/clientlogo-04_h7gavt.png" alt="" class="logocustomers"></a>
              </div>
              <div class="col-md-2">
                <a href="#"><img src="http://res.cloudinary.com/design-is-vital/image/upload/v1476028397/clientlogo-05_asy279.png" alt="" class="logocustomers"></a>
              </div>
              <div class="col-md-2">
                <a href="#"><img src="http://res.cloudinary.com/design-is-vital/image/upload/v1476028399/clientlogo-08_qledys.png" alt="" class="logocustomers"></a>
              </div>
              <div class="col-md-2">
                <a href="#"><img src="http://res.cloudinary.com/design-is-vital/image/upload/v1476028399/clientlogo-09_ljpamz.png" alt="" class="logocustomers"></a>
              </div>
              <div class="col-md-2">
                <a href="#"><img src="http://res.cloudinary.com/design-is-vital/image/upload/v1476028399/clientlogo-03_icjoxu.png" alt="" class="logocustomers"></a>
              </div>
              <div class="col-md-2">
                <a href="#"><img src="http://res.cloudinary.com/design-is-vital/image/upload/v1476028398/clientlogo-02_jjkjl8.png" alt="" class="logocustomers"></a>
              </div>
            </div>
          </div>
        </div>

        <hr>
      

        <div class="container pretainer">
          <div class="prerow">
                <h1>Nous designons la meilleure expérience pour vos utilisateurs. </h1>
                <p>Et nous développons le dispositif digitale adapté à vos besoins.</p>
          </div>

          <div class="rowhome">
            <div class="row">
              <div class="col-md-4">
                <img src="http://res.cloudinary.com/design-is-vital/image/upload/v1476028435/picto_uxdesign_a7pqwj.png" alt="UX Design" class="logocustomers">
                <h2>USER EXPERIENCE DESIGN</h2>
              </div>
              <div class="col-md-4">
                <br>
                <img src="http://res.cloudinary.com/design-is-vital/image/upload/v1476028435/picto_uidesign_w7gvhl.png" alt="Identité Visuelle" class="logocustomers">
                 <br>
                  <br>
                <h2>USER INTERFACE DESIGN</h2>
              </div>
              <div class="col-md-4">
                 <br>
                <img src="http://res.cloudinary.com/design-is-vital/image/upload/v1476028436/picto_brandidentity_y6yki2.png" alt="Web Application" class="logocustomers">
                 <br> <br>
                <h2>BRAND IDENTITY</h2>
              </div>
            </div>
          </div>
        </div>

        <hr>  

      
      <div class="projetshome">
        <div class="container">

              <div class="row">
                <div class="col-md-6 pull-left">
                  <h2> Refonte de l'application Kliner </h2>
                  <br>
                  <p> L'application Kliner permet de réserver son aide ménagère de manière ultra simple, en quelques clics. Design is Vital a accompagné l'équipe Kliner dans cette refonte en designant les 130 écrans de l'app. Tous les états de l'interface ont été prévues et imaginées de manière à gérer l'intégralité de l'expérience utilisateur. </p>

                  <a class="btn btn-primary btn-lg" href="http://designisvital.co/projets/kliner" role="button">DÉCOUVRIR LE PROJET KLINER</a>

                  <div class="testimonial">
                    <img src="http://res.cloudinary.com/design-is-vital/image/upload/v1476028408/Kliner_zu3rxd.png" alt="" class="logoauthor">
                    <p><i>"J'ai apprécié la très grande réactivité de Design is Vital et leur capacité à proposer la meilleure expérience."</i></p>
                      <div class="client">
                        <img src="http://res.cloudinary.com/design-is-vital/image/upload/v1476028405/brice_ns4p6d.png" class="left author">
                        <h5>Brice William Ngouo, Président @Kliner</h5>
                      </div>
                  </div>
                </div>

                <br>

                <div class="col-md-6 pull-right">

                  <img src="http://res.cloudinary.com/design-is-vital/image/upload/v1476028575/ProjetKliner2_k0tsne.png" class="projetshomeimg">

                </div>

              </div>
           </div>
        </div>   
      </div> 


      <hr>


      <div class="prerow">
          <h1>Les derniers projets de l'agence </h1>
          <p>Notre prochain projet sera peut-être le vôtre</p>
      </div>


    
      <div class="bodyprojet">
          <% @Projets.limit(15).in_groups_of(6, false).each do |group| %>
              <div class="row">
                <% group.each do |projet| %>
                    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                      <a href="<%= projet_path(projet.slug) %>">
                        <div class="thumbnail">
                          <img src="<%= projet.image.url(:medium) %>" alt="<% projet.title %>">
                          <span class="text"><span class="glyphicon glyphicon-eye-open"></span>Voir le projet</span>
                        </div>
                      </a>
                    </div>
                <% end %>
              </div>
          <% end %>
      </div>

      <hr>

      <div class="prerow">
        <h1>Vous avez un projet ? </h1>
        <br>
        <p><a class="btn btn-primary btn-lg" href="<%= contact_path %>" role="button">CHALLENGEZ-NOUS !</a>
        </p>
      </div>

      <hr>

      <div class="wrapper">
        <div class="prerow2">
          <h1>Chaque semaine des articles pour vous</h1>
          <p>Découvrez des techniques, des outils et des astuces</p>
        </div>
        <div class="container">
        <% @articles.last(3).in_groups_of(3, false).each do |group| %>
            <div class="row">
              <% group.each do |article| %>
                  <div class="col-xs-12 col-sm-4">
                      <a href="<%= articles_path(article.slug) %>"><div style="background: linear-gradient(-225deg, rgba(30,30,30,0.6) 30%, rgba(46,46,46,0.5) 80%), url('<%= article.image.url(:thumb) %>');" class="card">
                        <img src="<%= article.user.image.url(:thumb) %>" alt="" class="avatar-small card-user">
                      <div class="card-description">
                        <h3><%= article.title %></h3>
                        <p><%= truncate(article.soustitre, length: 45, escape: false) %></p>
                        </div>
                      </div>
                  </div></a>
                <% end %>
            </div>
          <% end %>
        </div>
    </div>





      

app/views/projet/index.html.erb
  <div class="block">
        <div class="container">
          <img class="logosmg" alt="logo designisvital" src="http://res.cloudinary.com/design-is-vital/image/upload/v1476101591/LOGO5-06_lmqkuj.png">
          <br>
          <h1>Nos Réalisations</h1>
          <p>Toutes nos réalisations sont faites avec amour à Paris.</p>
        </div>
  </div>

  <div class="prerow">
    <h1>Nos clients nous ont fait confiance. </h1>
        <p>Notre prochain projet sera peut-être le vôtre ?</p>
  </div>



  <div class="bodyprojet">
    <% @Projets.each do |group| %>
        <div class="row">
          <% group.each do |projet| %>
              <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                <a href="<%= projet_path(projet.slug) %>"><div class="thumbnail">
                  <img src="<%= projet.image.url(:medium) %>" alt="<% projet.title %>">
                  <span class="text"><span class="glyphicon glyphicon-eye-open"></span>Voir le projet</span>
                </div></a>
              </div>
          <% end %>
        </div>
    <% end %>
  </div>

app/views/projet/show.html.erb
<div class="show">
	<div class="block">
	    <div class="container">
        <%= image_tag("http://res.cloudinary.com/design-is-vital/image/upload/v1476101591/LOGO5-06_lmqkuj.png", :class => "logosmg")%>
	    	<br>
	        <h1>Projets</h1>
	        <p>réalisés par notre équipe</p>
	    </div>
	</div>

	<br>
	<div class="container">
		<h1><%= @projet.title %></h1>
    <br>
    <!--<hr class="top_title">-->
    <hr>
		<br>
		<p><%= simple_format(@projet.description).html_safe %></p>
		<br>
		<!-- <img src="<%= @projet.image.url(:medium) %>" alt="<% @projet.title %>">-->
	</div>
</div>

<hr>

     <div class="container">
     	<div class="prerow">
            <h1>Nous designons tous nos projets avec beaucoup d'amour </h1>
            <p>Voici quelques uns de nos derniers projets</p>
        </div>
    </div>

      <div class="bodyprojet">
          <% @Projets.limit(6).in_groups_of(6, false).each do |group| %>
              <div class="row">
                <% group.each do |projet| %>
                    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                      <a href="<%= projet_path(projet.slug) %>"><div class="thumbnail">
                        <img src="<%= projet.image.url(:medium) %>" alt="<% projet.title %>">
                      </div></a>
                    </div>
                <% end %>
              </div>
          <% end %>
      </div>